print("-----ARITHMETIC OPERATORS")
print("Addition")
print(20+10)
print("Subtraction")
print(20-10)
print("Multiplication")
print(20*10)
print("Division")
print(20/10)
print("Floor Division")
print(20//10)
print("Modulus")
print(20%10)
print("Exponentiation")
print(5**3)